usuario = [
               {"nombre":"Carla Estevez",
                "contraseña":"Carla123",
                "edad":"45",
                "sexo":"F",
                "peso": "90",
                "altura":"1.60",
                "restricciones alimenticias": None},

                {"nombre":"Dona Terra",
                "contraseña":"Dona123",
                "edad":"33",
                "sexo":"F",
                "peso": "66",
                "altura":"1.63",
                "restricciones alimenticias": "Vegetariana"},

                {"nombre":"Juan Martinelli",
                "contraseña":"Juan123",
                "edad":"21",
                "sexo":"M",
                "peso": "42",
                "altura":"1.80",
                "restricciones alimenticias": None},

                {"nombre":"Tomas Milke",
                "contraseña":"Tomas123",
                "edad":"19",
                "sexo":"M",
                "peso": "38",
                "altura":"1.83",
                "restricciones alimenticias":"Alergico al mani"},

                {"nombre":"Robbie Bey",
                "contraseña":"Robbie123",
                "edad":"13",
                "sexo":"M",
                "peso": "26",
                "altura":"1.63",
                "restricciones alimenticias": "Celiaco"},

                {"nombre":"Claudia Tros",
                "contraseña":"Claudia123",
                "edad":"60",
                "sexo":"F",
                "peso": "120",
                "altura":"1.50",
                "restricciones alimenticias": None},

                {"nombre":"Emma Bindel",
                "contraseña":"Emma123",
                "edad":"20",
                "sexo":"F",
                "peso": "40",
                "altura":"1.42",
                "restricciones alimenticias": "Alergica al tomate"},

                {"nombre":"Kiara Perkins",
                "contraseña":"Kiara123",
                "edad":"13",
                "sexo":"F",
                "peso": "26",
                "altura":"1.61",
                "restricciones alimenticias": None},

                {"nombre":"Gal Sortes",
                "contraseña":"Gal123",
                "edad":"23",
                "sexo":"F",
                "peso": "46",
                "altura":"1.43",
                "restricciones alimenticias": "Celiaca"},

                {"nombre":"Mijal Benitez",
                "contraseña":"Mijal123",
                "edad":"15",
                "sexo":"F",
                "peso": "30",
                "altura":"1.45",
                "restricciones alimenticias": "Vegana"},

                {"nombre":"Kevin Tel",
                "contraseña":"Kevin123",
                "edad":"50",
                "sexo":"M",
                "peso": "100",
                "altura":"1.70",
                "restricciones alimenticias": "Intolerante a la lactosa"},

                {"nombre":"Maximo Zas",
                "contraseña":"Maximo123",
                "edad":"53",
                "sexo":"M",
                "peso": "114",
                "altura":"1.54",
                "restricciones alimenticias": "Vegetariano"},

                {"nombre":"Yanina Arias",
                "contraseña":"Yanina123",
                "edad":"90",
                "sexo":"F",
                "peso": "180",
                "altura":"1.78",
                "restricciones alimenticias": "Alergica a la palta"},

                {"nombre":"Tamara Ruiz",
                "contraseña":"Tamara123",
                "edad":"86",
                "sexo":"F",
                "peso": "70",
                "altura":"1.78",
                "restricciones alimenticias": "Vegetariana"},

                {"nombre":"Solana Jaichenco",
                "contraseña":"Solana123",
                "edad":"57",
                "sexo":"F",
                "peso": "58",
                "altura":"1.75",
                "restricciones alimenticias": None},

                {"nombre":"Magali Ringler",
                "contraseña":"Magali123",
                "edad":"49",
                "sexo":"F",
                "peso": "50",
                "altura":"1.59",
                "restricciones alimenticias": None},

                {"nombre":"Valentina Pinto",
                "contraseña":"Valentina123",
                "edad":"10",
                "sexo":"F",
                "peso": "73",
                "altura":"1.71",
                "restricciones alimenticias": None},

                {"nombre":"Federico Jaraj",
                "contraseña":"Federico123",
                "edad":"94",
                "sexo":"M",
                "peso": "60",
                "altura":"2.00",
                "restricciones alimenticias": None},

                {"nombre":"Gaston Madrin",
                "contraseña":"Gaston123",
                "edad":"66",
                "sexo":"M",
                "peso": "82",
                "altura":"1.62",
                "restricciones alimenticias": "Celiaco"},

                {"nombre":"Gabriel Perez",
                "contraseña":"Gabriel123",
                "edad":"44",
                "sexo":"M",
                "peso": "88",
                "altura":"1.84",
                "restricciones alimenticias": "Intolerante a la verdura cruda"},

                {"nombre":"Daniel Lincoln",
                "contraseña":"Daniel123",
                "edad":"87",
                "sexo":"M",
                "peso": "67",
                "altura":"1.76",
                "restricciones alimenticias": "Vegano"},

                {"nombre":"Victor Leda",
                "contraseña":"Victor123",
                "edad":"30",
                "sexo":"M",
                "peso": "60",
                "altura":"1.63",
                "restricciones alimenticias": "Alergico a la nuez"},

                {"nombre":"Adrian Lucero",
                "contraseña":"Adrian123",
                "edad":"40",
                "sexo":"M",
                "peso": "86",
                "altura":"1.64",
                "restricciones alimenticias": "Vegetariano"},

                {"nombre":"Leandro Repis",
                "contraseña":"Leandro123",
                "edad":"29",
                "sexo":"M",
                "peso": "58",
                "altura":"1.50",
                "restricciones alimenticias": None},

                {"nombre":"Martina Teitel",
                "contraseña":"Martina123",
                "edad":"22",
                "sexo":"F",
                "peso": "63",
                "altura":"1.62",
                "restricciones alimenticias": None},

                {"nombre":"Mariana Piczman",
                "contraseña":"Mariana123",
                "edad":"58",
                "sexo":"F",
                "peso": "65",
                "altura":"1.85",
                "restricciones alimenticias": None},

                {"nombre":"Veronica Jarosky",
                "contraseña":"Veronica123",
                "edad":"9",
                "sexo":"F",
                "peso": "25",
                "altura":"1.35",
                "restricciones alimenticias": None},

                {"nombre":"Mora Glit",
                "contraseña":"Mora123",
                "edad":"63",
                "sexo":"F",
                "peso": "59",
                "altura":"1.68",
                "restricciones alimenticias": None},

                {"nombre":"Nicole Tokla",
                "contraseña":"Nicole123",
                "edad":"95",
                "sexo":"F",
                "peso": "53",
                "altura":"1.66",
                "restricciones alimenticias": None},

                {"nombre":"Martin Blarg",
                "contraseña":"Martin123",
                "edad":"37",
                "sexo":"M",
                "peso": "94",
                "altura":"1.95",
                "restricciones alimenticias": "Vegano"}

]